In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
df = pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.shape

(5572, 2)

In [5]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
df['spam'].value_counts()

0    4825
1     747
Name: spam, dtype: int64

In [9]:
# create train test split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.25)

In [10]:
x_train.describe()

count                       4179
unique                      3920
top       Sorry, I'll call later
freq                          22
Name: Message, dtype: object

In [11]:
# find word count and store data as a matrix
cv = CountVectorizer()

In [12]:
x_train_count = cv.fit_transform(x_train.values)

In [13]:
x_train_count

<4179x7472 sparse matrix of type '<class 'numpy.int64'>'
	with 55266 stored elements in Compressed Sparse Row format>

In [14]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
x_train_count.shape

(4179, 7472)

In [16]:
# train Model

model = MultinomialNB()

In [17]:
model.fit(x_train_count, y_train)

MultinomialNB()

In [18]:
email_ham = ["hey wanna meet up for the game"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [19]:
email_spam = ["reward money click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [20]:
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9827709978463748